---
title: "Covid daily"
author: "Marco Arthur"
date: "3/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(tsibble)
library(lubridate)
library(gridExtra)
library(purrr)
library(plotly)
library(stringr)

# path to data for daily reports
path <- file.path("data", "jhopkins", "covid", "csse_covid_19_data", "csse_covid_19_daily_reports")
daily_files <- list.files(path)

# find the most recent
most_recent <- max(mdy(daily_files), na.rm = T)

most_recent <- str_c(  ifelse(str_length(month(most_recent)) == 1, str_c("0", month(most_recent)), month(most_recent)),
  day(most_recent),
  year(most_recent),  sep = "-")
most_recent <- str_c(most_recent, ".csv")

# time series file path
time_series_file <- file.path("data", "jhopkins", "covid", "csse_covid_19_data", "csse_covid_19_time_series", "time_series_covid19_deaths_global.csv")

covid_ds <-
  read_csv(file.path(path, most_recent))
time_series_covid19_deaths_global <-
  read_csv("data/jhopkins/covid/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")

```

## Dataset

We are using dataset from John Hopkins CSSE for global desease. The github
repository with the raw data can be found
[here](https://github.com/CSSEGISandData/COVID-19)

The graph bellow shows Brazil and Italy death count
```{r}


extract_ts <- function( country, include_zero = T ) {
  df <- time_series_covid19_deaths_global %>%
  filter( `Country/Region` == country)

  df <- map_if(df, is.numeric, sum) %>% as_tibble()
  tmp <- as_tibble(cbind(days = names(df), t(df)))
  tmp <- tmp[ -c(1:4), ] # remove header
  class(tmp[[2]]) <- "double" # convert to double
  # rename death count
  tmp <- tmp %>%
    rename( deaths = V2) 
  # create days for time series
  tmp <- tmp %>%
    mutate( days = parse_date(days, format = "%m/%d/%y"))
  
  # create the time series
  ts <- tmp %>%
    as_tsibble( index = days )
  
  if ( include_zero )
    return <- ts
  else
    return <- ts %>% filter( deaths > 0 )
}

do_plots <- function(countries, plotly = F ) {
  dfs <- map(countries, extract_ts)

  if ( ! plotly ) {
    plot_me <- function(df) {
      df %>% 
        ggplot( aes( x = days, y = deaths)) +
        geom_line()
      }
  } else {
    plot_me <- function(df) {
      df %>% 
        plot_ly( x = ~days, y = ~deaths, mode = "lines")
      }
  }

  plots <- map(dfs, plot_me)
}

compare_countries <- function ( countries_list, plotly = F ) {
  plots <- do_plots(countries_list, plotly)

  # add label to plot
  for( i in seq_along(plots)) {
    if( plotly )
      plots[[i]] <- plots[[i]] %>% layout( title = countries_list[[i]] )
    else
      plots[[i]] <- plots[[i]] + labs(title = countries_list[[i]])
  }

  # arrange in N-columns the plots
  if(plotly) {
    # put labels each line
    for( i in seq_along(plots)) {
      plots[[i]] <- plots[[i]] %>% add_lines( name = countries_list[[i]] )
    }
    do.call("subplot", plots)
  }
  else { 
    args_list = c(plots, ncol = length(countries_list))
    do.call("grid.arrange", args_list)  
  }
}

# make plots for brazil and italy
compare_countries(c("Brazil", "Italy"))
```


Comparing US and China
```{r}
compare_countries(c("US", "China"))
```

Comparing Brazil and US

```{r}
compare_countries(c("Brazil","US"), plotly = T)
```

